# Generated by Django 4.0.5 on 2022-06-30 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resposta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='data_resposta',
            field=models.DateTimeField(default=datetime.date(2022, 6, 30)),
        ),
    ]
