# Generated by Django 4.0.5 on 2022-06-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resposta', '0002_alter_resposta_data_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='data_resposta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
