# Generated by Django 4.0.5 on 2022-06-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('o_atendimento_foi', models.CharField(choices=[('Muito satisfeito', 'Muito satisfeito'), ('Satisfeito', 'Satisfeito'), ('Neutro', 'Neutro'), ('Insatisfeito', 'Insatisfeito'), ('Muito insatisfeito', 'Muito insatisfeito')], default='Neutro', max_length=20)),
                ('cadastrado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atendimento', models.CharField(max_length=80)),
            ],
        ),
    ]
