# Generated by Django 4.0.5 on 2022-06-30 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão'},
        ),
        migrations.RemoveField(
            model_name='questao',
            name='cadastrado',
        ),
        migrations.AddField(
            model_name='questao',
            name='cadastrado_em',
            field=models.DateField(default=datetime.date(2022, 6, 29)),
        ),
        migrations.AddField(
            model_name='tipo_atendimento',
            name='descricao',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
