# Generated by Django 4.0.5 on 2022-06-30 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0002_alter_questao_options_remove_questao_cadastrado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AddField(
            model_name='questao',
            name='tipo_atendimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questao.tipo_atendimento'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='cadastrado_em',
            field=models.DateField(default=datetime.date(2022, 6, 30)),
        ),
    ]
