# Generated by Django 4.0.5 on 2022-06-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0003_alter_questao_options_questao_tipo_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='cadastrado_em',
            field=models.DateField(auto_now_add=True),
        ),
    ]
