# Generated by Django 4.0.5 on 2022-06-30 00:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questao', '0002_alter_questao_options_remove_questao_cadastrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('data_criada', models.DateField(default=datetime.date(2022, 6, 29))),
                ('validade', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pesquisa',
            },
        ),
        migrations.CreateModel(
            name='Item_pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pesquisa.pesquisa')),
                ('nome_questao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questao.questao')),
            ],
        ),
    ]
