# Generated by Django 4.0.5 on 2022-06-30 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_pesquisa',
            options={'verbose_name': 'Item_pesquisa', 'verbose_name_plural': 'Itens_pesquisa'},
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='data_criada',
            field=models.DateField(default=datetime.date(2022, 6, 30)),
        ),
    ]
