# Generated by Django 4.0.5 on 2022-07-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0002_alter_item_pesquisa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='data_criada',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
